services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CRAWLER_URL=http://crawler:3000
        - NEXT_PUBLIC_DATA_PERSISTENCE_URL=http://data-persistence:3000
        - NEXT_PUBLIC_OCR_URL=http://image-ocr:3000
        - NEXT_PUBLIC_DS_URL=http://ds-services:3000
    container_name: backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - data-persistence
      - crawler
      - ds-services

  image-ocr:
    build:
      context: ./image-ocr
      dockerfile: Dockerfile
    container_name: translayze-image-ocr
    ports:
      - "8001:3000"
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata/
    restart: unless-stopped

  ds-services:
    build:
      context: ./ds-services
      dockerfile: Dockerfile
    container_name: translayze-ds-services
    ports:
      - "8002:3000"
    environment:
      - DEEPSEEK_API_KEY=sk-c09798b2597c4769879fb29209e3f756
    restart: unless-stopped

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: translayze-crawler
    ports:
      - "8003:3000"
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    restart: unless-stopped

  data-persistence:
    build:
      context: ./data-persistence
      dockerfile: Dockerfile
    container_name: translayze-data-persistence
    ports:
      - "8004:3000"
    environment:
      - MONGODB_URI=mongodb+srv://guest:qazwsxedc@default.ktjsvq6.mongodb.net/
    restart: unless-stopped

volumes:
  mongodb_data:
